import '../styles/global.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import ReactQueryProvider from '@/utils/ReactQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const font = localFont({
  src: '../styles/fonts/PretendardVariable.woff2',
  display: 'swap',
});

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <ReactQueryProvider>
      <html
        lang="ko"
        className={font.className}
      >
        <body>{children}</body>
      </html>
    </ReactQueryProvider>
  );
};

export default RootLayout;
